name: Check PR
on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Checking Conventional Commits
        run: node ./scripts/check-conventional-commits/command.mjs
        env:
          REF: ${{ github.ref }}

      - name: Test
        run: |
          node ./scripts/build-libs/command.mjs
          yarn run test

      - name: Hash Current Branch Name
        id: hash_curret_branch_name
        run: |
          hashed_name=$(echo -n "${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" | base64)
          echo "hashed=${hashed_name}">> $GITHUB_OUTPUT

      - name: Upload Build Meta
        uses: actions/upload-artifact@v4
        with:
          name: ${{steps.hash_curret_branch_name.outputs.hashed}}
          path: |
            **/**/**.build.json
            !**/node_modules/**
          retention-days: 30
          overwrite: true

      # for preview deployment for specific project, add vercel project id in environment section
      - name: Preview Deployment
        id: deploy
        run: |
          yarn global add vercel
          yarn run deploy
        env:
          REF: ${{ github.ref }}
          GH_TOKEN: ${{ github.token }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_WIDGET_CONFIG: ${{ secrets.VERCEL_PROJECT_WIDGET_CONFIG }} # widget playground
          VERCEL_PROJECT_WIDGET_APP: ${{ secrets.VERCEL_PROJECT_WIDGET_APP }} # widget app
          VERCEL_PROJECT_STORYBOOK: ${{ secrets.VERCEL_PROJECT_STORYBOOK }} # storybook

          ENABLE_PREVIEW_DEPLOY: true

    outputs:
      # the structure of output variable is {packageNameWithoutScope}-url like: widget-app-url
      app_url: ${{ steps.deploy.outputs.widget-app-url }}
      playground_url: ${{ steps.deploy.outputs.widget-playground-url }}
      storybook_url: ${{ steps.deploy.outputs.storybook-url }}

  # add job for each project that you want has preview deployment
  app-preview:
    runs-on: ubuntu-latest
    needs: check
    environment:
      name: app-preview
      url: ${{ steps.seturl.outputs.url }}
    steps:
      - name: Extract Preview URL
        id: seturl
        run: |
          echo "url=${{ needs.check.outputs.app_url }}">> $GITHUB_OUTPUT
          echo "Preview URL: ${{ needs.check.outputs.app_url}}"

  playground-preview:
    runs-on: ubuntu-latest
    needs: check
    environment:
      name: playground-preview
      url: ${{ steps.seturl.outputs.url }}
    steps:
      - name: Extract Preview URL
        id: seturl
        run: |
          echo "url=${{ needs.check.outputs.playground_url }}">> $GITHUB_OUTPUT
          echo "Preview URL: ${{ needs.check.outputs.playground_url}}"

  storybook-preview:
    runs-on: ubuntu-latest
    needs: check
    environment:
      name: storybook-preview
      url: ${{ steps.seturl.outputs.url }}
    steps:
      - name: Extract Preview URL
        id: seturl
        run: |
          echo "url=${{ needs.check.outputs.storybook_url }}">> $GITHUB_OUTPUT
          echo "Preview URL: ${{ needs.check.outputs.storybook_url}}"

  analyze-bundle:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Hash Current Branch Name
        id: hash_target_branch_name
        run: |
          hashed_name=$(printf "%s" "${{ github.base_ref }}" | base64)
          echo "hashed=${hashed_name}">> $GITHUB_OUTPUT

      - name: Download Current Branch Build Meta
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: ${{steps.hash_curret_branch_name.outputs.hashed}}
          path: 'current-branch'

      - name: Set Up jq
        run: sudo apt-get install -y jq

      - name: List Artifacts
        id: list_artifacts
        run: |
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/artifacts" \
          | jq --arg ARTIFACT_NAME "${{ steps.hash_target_branch_name.outputs.hashed }}" '.artifacts | map(select(.name == $ARTIFACT_NAME)) | .[0]' > artifact.json

      - name: Extract Target Branch Artifact Download URL
        id: get_artifact_url
        run: |
          cat artifact.json
          echo "artifact_url=$(jq -r .archive_download_url artifact.json)" >> $GITHUB_OUTPUT

      - name: Download Target Branch Artifact
        if: steps.get_artifact_url.outputs.artifact_url != 'null'
        run: |
          curl -L -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -o artifact.zip "${{ steps.get_artifact_url.outputs.artifact_url }}"
          unzip artifact.zip -d ./target-branch

      - name: Analyze Bundles And Create Report
        run: node ./scripts/analyze-bundle/command.mjs current-branch target-branch
